# Generated by Django 5.2.17 on 2026-10-01 13:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("learning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("single", "Один правильный ответ"),
                            ("multiple", "Несколько правильных ответов"),
                            ("text", "Развёрнутый ответ (проверяет администратор)"),
                        ],
                        default="single",
                        max_length=16,
                        verbose_name="Тип вопроса",
                    ),
                ),
                ("text", models.TextField(verbose_name="Вопрос")),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        upload_to="questions/%Y/%m/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "points",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Баллы"),
                ),
                (
                    "explanation",
                    models.TextField(blank=True, verbose_name="Пояснение к ответу"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempts_allowed",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Количество попыток"
                    ),
                ),
                (
                    "available_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Доступен с"
                    ),
                ),
                (
                    "available_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Доступен до"
                    ),
                ),
                (
                    "is_revoked",
                    models.BooleanField(default=False, verbose_name="Отозван"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Доступ к тесту",
                "verbose_name_plural": "Доступы к тестам",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=500, verbose_name="Вариант ответа"),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Верный"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="exams.question",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание / инструкция"),
                ),
                (
                    "time_limit_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Пусто — без ограничения.",
                        null=True,
                        verbose_name="Ограничение по времени, мин",
                    ),
                ),
                (
                    "pass_percent",
                    models.PositiveSmallIntegerField(
                        default=70, verbose_name="Проходной балл, %"
                    ),
                ),
                (
                    "questions_per_attempt",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Пусто — все вопросы. Иначе — случайная выборка указанного размера.",
                        null=True,
                        verbose_name="Вопросов в попытке",
                    ),
                ),
                (
                    "shuffle_questions",
                    models.BooleanField(
                        default=True, verbose_name="Перемешивать вопросы"
                    ),
                ),
                (
                    "shuffle_choices",
                    models.BooleanField(
                        default=True, verbose_name="Перемешивать варианты ответов"
                    ),
                ),
                (
                    "show_results",
                    models.BooleanField(
                        default=False,
                        help_text="По умолчанию результат видит только администратор.",
                        verbose_name="Показывать результат пользователю",
                    ),
                ),
                (
                    "show_correct_answers",
                    models.BooleanField(
                        default=False,
                        help_text="Работает только вместе с «Показывать результат».",
                        verbose_name="Показывать правильные ответы",
                    ),
                ),
                (
                    "require_course_completion",
                    models.BooleanField(
                        default=False,
                        help_text="Тест откроется, когда пользователь изучит все материалы привязанного курса.",
                        verbose_name="Только после изучения курса",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Необязательно. Оставьте пустым для отдельного теста (например, для кандидатов).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tests",
                        to="learning.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Тест",
                "verbose_name_plural": "Тесты",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="exams.test",
            ),
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "В процессе"),
                            ("submitted", "Завершён"),
                            ("timed_out", "Время вышло"),
                        ],
                        default="in_progress",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("question_order", models.JSONField(default=list)),
                ("choice_order", models.JSONField(default=dict)),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "max_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "percent",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                ("passed", models.BooleanField(null=True)),
                ("needs_review", models.BooleanField(default=False)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="exams.assignment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="exams.test",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка",
                "verbose_name_plural": "Попытки",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="assignment",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="exams.test",
            ),
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_answer", models.TextField(blank=True)),
                ("is_correct", models.BooleanField(null=True)),
                (
                    "points",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="exams.attempt",
                    ),
                ),
                (
                    "selected",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="exams.choice"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="exams.question",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("attempt", "question"), name="uniq_attempt_answer"
                    )
                ],
            },
        ),
    ]
