# Generated by Django 5.2.17 on 2026-10-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="source_hash",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
